version: '2'

services:
  ebot: 
    image: jamesyale/docker-ebot-csgo
    ports: 
      - "12360:12360"
      - "12361:12361"
    links:
      - "mysql:mysql"
    depends_on:
      - ebotweb
    networks:
      - anet
  ebotweb: 
    image: jamesyale/docker-ebot-csgo-web
    links: 
      - "mysql:mysql"
    ports: 
      - "8081:80"
    networks:
      - anet
  mysql: 
    environment: 
      - MYSQL_DATABASE=ebotv3
      - MYSQL_USER=ebotv3
      - MYSQL_PASSWORD=ebotv3
      - MYSQL_ROOT_PASSWORD=ebotv3
    image: mysql
    networks:
      - anet
networks:
  anet:
    driver: bridge
